[package]
name = "runnel-raft"
version.workspace = true
edition.workspace = true

[dependencies]
openraft.workspace = true
runnel-engine = { path = "../runnel-engine" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile = "3.15"
