[package]
name = "runnel-client"
version.workspace = true
edition.workspace = true

[dependencies]
runnel-protocol = { path = "../runnel-protocol" }
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
rustls-native-certs = "0.8"
rustls-pemfile = "2"
thiserror.workspace = true
tokio.workspace = true
tokio-rustls = { version = "0.26", default-features = false, features = ["ring"] }
zeroize = "1"
