[package]
name = "runnel-server"
version.workspace = true
edition.workspace = true

[features]
instrumentation = [
    "runnel-core/instrumentation",
    "runnel-engine/instrumentation",
    "runnel-raft/instrumentation",
]

[[bin]]
name = "runnel"
path = "src/main.rs"

[dependencies]
axum.workspace = true
clap.workspace = true
runnel-core = { path = "../runnel-core" }
runnel-engine = { path = "../runnel-engine" }
runnel-raft = { path = "../runnel-raft" }
runnel-protocol = { path = "../runnel-protocol" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
serde_json.workspace = true
tempfile = "3.15"
